# Generated by Django 3.2 on 2022-06-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='queston_text',
            new_name='question_text',
        ),
    ]
